In [1]:
import numpy as np

In [3]:
X = np.random.randint(0, 5001, size=(1000, 20))

In [5]:
X

array([[1809, 1919, 4700, ..., 2510, 2261, 4141],
       [3315, 3565,  761, ...,  911, 3663, 2245],
       [ 196, 3928, 3173, ..., 2977, 3409,  520],
       ...,
       [ 233, 1403, 1530, ..., 1384,  838, 3134],
       [ 301,  509,  619, ..., 3337, 4708, 4013],
       [4511, 4102, 1149, ...,  655, 1832, 1086]])

In [7]:
X.shape

(1000, 20)

In [9]:
avg_cols = np.mean(X, axis=0)

In [11]:
avg_cols

array([2386.512, 2466.169, 2492.783, 2426.221, 2438.413, 2574.067,
       2504.261, 2462.811, 2464.884, 2541.308, 2516.227, 2515.751,
       2501.025, 2519.91 , 2524.364, 2536.84 , 2527.405, 2422.768,
       2468.701, 2484.813])

In [13]:
avg_cols.shape

(20,)

In [15]:
std_cols = np.std(X, axis=0)

In [17]:
std_cols

array([1450.64898161, 1426.89748   , 1453.53997052, 1444.9748988 ,
       1472.78904071, 1403.91866521, 1462.6763213 , 1443.62267483,
       1410.12015961, 1398.43817065, 1430.77159235, 1422.70961795,
       1482.25111246, 1438.82946102, 1437.5254563 , 1443.34593442,
       1424.81397838, 1410.96762336, 1469.09765217, 1422.88621331])

In [19]:
std_cols.shape

(20,)

In [21]:
X_norm = (X - avg_cols) / std_cols

In [23]:
X_norm

array([[-0.39810596, -0.38346763,  1.51851139, ...,  0.06182424,
        -0.14137998,  1.16396307],
       [ 0.64005008,  0.77008406, -1.19142441, ..., -1.0714406 ,
         0.81294732, -0.16853983],
       [-1.51002209,  1.02448215,  0.46797268, ...,  0.39280278,
         0.64005207, -1.38086446],
       ...,
       [-1.48451626, -0.74509137, -0.66237119, ..., -0.73620966,
        -1.11000177,  0.4562466 ],
       [-1.43764069, -1.37162552, -1.28911694, ...,  0.64794683,
         1.52426831,  1.07400506],
       [ 1.46450866,  1.14642504, -0.92448988, ..., -1.25287637,
        -0.43339597, -0.98308142]])

In [31]:
avg_X_norm = np.mean(X_norm)

In [33]:
avg_X_norm

-2.3092638912203255e-17

In [35]:
min = np.min(X_norm, axis = 0)

In [37]:
min

array([-1.64513403, -1.71783119, -1.71428585, -1.67492252, -1.65292716,
       -1.83348727, -1.7121088 , -1.70460817, -1.74232244, -1.81653222,
       -1.75445684, -1.76195547, -1.68056882, -1.74927611, -1.73587465,
       -1.75761052, -1.77314726, -1.71497061, -1.67769719, -1.74631884])

In [39]:
avg_min = np.mean(min)

In [41]:
avg_min

-1.728301797169852

In [43]:
max = np.max(X_norm, axis = 0)

In [45]:
max

array([1.79884178, 1.77155755, 1.72421609, 1.77842466, 1.73859727,
       1.72726032, 1.70423146, 1.75612994, 1.79070981, 1.75602472,
       1.73526859, 1.74473341, 1.68255903, 1.72368586, 1.71241211,
       1.70656247, 1.73467908, 1.82160948, 1.72234909, 1.75993483])

In [47]:
avg_max = np.mean(max)

In [49]:
avg_max

1.744489376775951

In [53]:
#We create a random permutation of integers 0 to 4
row_indices = np.random.permutation(X_norm)

In [55]:
row_indices

array([[ 0.24781184,  0.13724252, -0.7972144 , ..., -1.03246026,
        -1.22844182,  0.91657856],
       [-0.73795385,  1.43025762,  0.31386615, ..., -0.98922752,
        -0.84249063, -0.27606775],
       [ 1.5079375 ,  0.85768671,  1.67468185, ...,  0.96404196,
         0.43788716,  1.4507042 ],
       ...,
       [-0.66419376, -1.0401371 ,  1.30042313, ...,  1.12846813,
         1.18392334,  0.8413793 ],
       [ 0.5752515 ,  0.81283415,  1.51438354, ..., -0.51508482,
         1.48819175, -0.22616917],
       [-1.20808826, -1.02331739,  0.20585399, ..., -0.1040194 ,
         0.57470584, -0.52626344]])

In [59]:
row_indices.shape

(1000, 20)

In [85]:
# Create a Training Set
X_train = int(len(row_indices) * 0.6)

In [87]:
X_train

600

In [65]:
# Create a Cross Validation Set
X_crossVal = int(len(row_indices) * 0.2)

In [71]:
X_crossVal

200

In [67]:
# Create a Test Set
X_test = int(len(row_indices) * 0.2)

In [73]:
X_test

200