In [3]:
import numpy as np

In [6]:
# Replace None with appropriate code
x = np.linspace(2,32,16)

In [9]:
x.shape

(16,)

In [12]:
x.reshape(4,4)

array([[ 2.,  4.,  6.,  8.],
       [10., 12., 14., 16.],
       [18., 20., 22., 24.],
       [26., 28., 30., 32.]])

In [15]:
x = np.arange(1,26).reshape(5,5)

In [18]:
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [21]:
x%2==1

array([[ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True]])