In [9]:
#Use Broadcasting to create a 4 x 4 ndarray that has its first column full of `1s`, 
#its second column full of `2s`, its third column full of `3s`, etc

In [11]:
import numpy as np
x = np.array([1,2,3,4])

In [13]:
x

array([1, 2, 3, 4])

In [16]:
x2 = x.reshape(4,1)

In [18]:
x2

array([[1],
       [2],
       [3],
       [4]])

In [21]:
result = x2*np.ones((1, 4), dtype=int)

In [23]:
result

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4]])