In [ ]:
"""
Use Broadcasting to create a 4 x 4 ndarray that has its first column full of `1s`, 
its second column full of `2s`, its third column full of `3s`, etc
"""

In [6]:
import numpy as np
x = np.array([1,2,3,4])

In [8]:
x

array([1, 2, 3, 4])

In [17]:
x2 = x.reshape(4,1)

In [19]:
x2

array([[1],
       [2],
       [3],
       [4]])

In [29]:
result = x2*np.ones((1, 4), dtype=int)

In [31]:
result

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4]])